### ISSUE TITLE
Xenogears USA SLUS-00664 memcard pro cannot be read after saving in-game

### ISSUE THREAD

**Issue by kimbapslice** [AppCakeLtd/memcardpro-bugs#1]
Setup:
PSX Scph-5501, xstation 1.20, ps1digital 1.5.2
Memcard pro 1.0.0 beta2, 32gb samsung evo micro sd
Xenogears USA SLUS-00664 disk 1 or 2

Issue:
After saving or copying a save in game, opening up the file manager again will display a blank memory card (with the memcard pro). Saving to an open block or overwriting an existing save gives the same result. Removing the Memcard Pro and reinserting will allow the game to show the saves again. Xenogears has its own memory card manager: Load, Copy, Delete, Save. You can save up to 15 blocks per card. Delete seems to work ok. It is the saving and copying.

I have also tested this on a Scph-1001(psnee) and PS2 Scph-39001 (stock) with original print disks - same issue.

**Comment by ThanosSiopoudis** [comment]
Confirmed and fixed in upcoming version

**Comment by kimbapslice** [comment]
Verified working/fixed in 1.0.1
