### ISSUE TITLE
SCPH-5501 issues with copying memory card files to different VMCs in PS1 memory card manager

### ISSUE THREAD

**Issue by mfncl9991** [AppCakeLtd/memcardpro-bugs#3]
I'm using my memcardpro with Xstation and so went through an exercise to migrate save data off of existing memory cards, with the goal of getting the old memory card data into per-game specific folders on the SD card.
This was a pretty labor intensive process because I had to make sure each individual save game got copied to its own VMC, and then making sure it was placed in correct folders for each game on the SD card.
During the migration I uncovered what seems to be a bug:

When I copy a save file on the PS1 card manager, then change to a new VMC, the next save game I try to copy over did not copy (the copy animation simply does not happen) I have to reset the console to be able to copy more than one save game after switching to a new VMC. So to get all my save games copied over from one physical memcard to 10 or so VMCs, I had to repeatedly power cycle the console 10 times.

Console is an NTSC xstation modded SCPH-5501. Tried multiple SD cards and saw the same behavior (unbranded and a Samsung evo card, tried both formatted as FAT32 and as exFAT). Official Sony memory cards are the source.

No problems with switching VMC in-game and writing/reading from the different VMC.
Could be an issue with the BIOS/memcard manager of the SCPH-5501? This BIOS (at least from a UI/UX perspective) is different from a PAL PSX BIOS.

**Comment by kimbapslice** [comment]
I am also experiencing the same issue.
Setup:
Scph-5501
ps1digital 1.5.2
Xstation 1.2.0
32gb fat32 Samsung Evo/Also tried 32gb Sony Class 10 Micro sd

Copying from Madcatz 32X psx card.

**Comment by ThanosSiopoudis** [comment]
Beta is coming up, which maybe fixes this. It will be available through the #memcardpro-discussion channel on Classic Gaming Discord

**Comment by mfncl9991** [comment]
Thanks @ThanosSiopoudis The beta posted to the discord fixed it for me
